<pre class='metadata'>
Title: IDX Interoperability Testing Guidance
Shortname: idx-interop-testing
Status: LD
ED: https://sine-fdn.github.io/interop-testing.html
Canonical URL: ED
Editor: Raimundo Henriques, https://sine.foundation, raimundo@sine.foundation
Repository: sine-fdn/idx-protocol
Abstract: Guidance for interoperability testing in the [IDX protocol](./index.html) context
Markup Shorthands: markdown yes
Boilerplate: omit conformance, omit copyright
</pre>

# About # {#about}

This document defines a [=Pilot Testing=] process to test a [=Target host system=] against the [[!IDX]] Protocol. By passing the tests defined in [[#mandatory-tests]], a system is defined as passing the pilot testing.

# Definitions # {#definitions}

: <dfn>Host System</dfn>
:: Any software implementation conforming to the IDX protocol

: <dfn>Target Host System</dfn>
:: The [=host system=] being tested

: <dfn>Tester Host System</dfn>
:: The [=host system=] performing the tests

: <dfn data-noexport>Bilateral Testing</dfn>
:: The execution of the interoperability testing process defined through this document by two systems, with each system taking the role of a [=Target Host system=] and a [=Tester Host system=] 

: <dfn>Interoperable</dfn>
     Note: the goal of bilateral testing is to assert the interoperability between 2 independent implementations of the IDX Protocol.

# Introduction # {#introduction}

Generally, interoperability testing is performed to verify the interoperability of independent implementations ([=host systems=]).

Within the scope of this document, <dfn>Pilot Testing</dfn> is an interoperabilty testing process, performed by executing and passing the tests further defined in [[#mandatory-tests]].

A host system, acting as a [=target host system=], has successfully passed the [=pilot testing=] if it passed all mandatory tests ([[#mandatory-tests]]).

Note: It is RECOMMENDED to perform the Pilot Testing process as a [=bilateral testing=] process between two independent parties and implementations.

Note: It is RECOMMENDED for the parties to also test and document the results of the optional tests defined in [[#recommended-tests]].

## Bilateral Testing Process  ## {#bilateral-testing-process}

Pilot testing SHOULD be a [=bilateral testing=] process by executing the following steps:

**Phase 1**

1. Acting as the [=target host system=], host system A (e.g., Leonardo) provides host system B (e.g., ImpactableX) with
    1. The host url of their API
    1. A username
    1. A password
1. Acting as the **tester host system**, host system B (e.g., ImpactableX) performs both
        [[#mandatory-tests]] against host system A (e.g., Leonardo), keeping track of whether they are
        successful or otherwise.
1. The [=tester host system=], host system B documents the test outcome according to the instructions in
        [[#test-output]].

**Phase 2**

1. Acting as the [=target host system=], host system B (e.g., ImpactableX) provides host system A (e.g., Leonardo) with
    1. The host url of their API
    1. A username
    1. A password
1. Acting as the [=tester host system=], host system A (e.g., Leonardo) performs both [[#mandatory-tests]] agains host system B (e.g., ImpactableX), keeping track of whether they are successful or otherwise.
1. The tester host system, host system A documents the test outcome according to the instructions in [[#test-output]].

## Mandatory Tests ## {#mandatory-tests}

: [Test Case 001: AuthEndpoint Discovery](./index.html#tc-001)
:: Tests the target host system's ability to have a discoverable [AuthEndpoint](./index.html#authendpoint).

: [Test Case 002: Successful Authentication](./index.html#tc-002)
:: Tests the target host system's ability to [authenticate](./index.html#action-authenticate) a [data recipient](./index.html#data-recipient).

: [Test Case 005: Action OpportunityExchange without Limit](./index.html#tc-005)
:: Tests the target host system's ability to return [`Opportunity`](./index.html#elementdef-opportunity) data without a [Limit](./index.html#limit).

## Recommended Tests ## {#recommended-tests}

: [Test Case 003: Authentication with Invalid Credentials](./index.html#tc-003)
:: Tests the target host system's ability to handle invalid credentials during authentication.

: [Test Case 004: Malformed Authentication Request](./index.html#tc-004)
:: Tests the target host system's ability to handle malformed authentication requests.

: [Test Case 006: Action OpportunityExchange Pagination](./index.html#tc-006)
:: Tests the target host system's ability to paginate [`Opportunity`](./index.html#elementdef-opportunity) data.

: [Test Case 007: Action OpportunityExchange with Malformed Limit](./index.html#tc-007)
:: Tests the target host system's ability to handle a malformed `limit` parameter.

: [Test Case 008: Action OpportunityExchange with Invalid Token](./index.html#tc-008)
:: Tests the target host system's ability to handle an invalid access token.

: [Test Case 009: Action OpportunityExchange with Expired Token](./index.html#tc-009)
:: Tests the target host system's ability to handle an expired access token.

: [Test Case 010: Malformed OpportunityExchange Request](./index.html#tc-010)
:: Tests the target host system's ability to handle malformed requests to the `[Subpath]/1/opportunities`.

## Test Output ## {#test-output}

Once all tests are performed, the tester host system is asked to provide the IDX team with a document summarizing the outcome of the test.

We recommend that this document is JSON with the format specified [here](./index.html#test-output)
and that the (free form) `comments` field is used to describe why certain tests failed or were
skipped.

<div class=example>
    <pre highlight=json>
        {
            "targetHostSystem": "example target host system",
            "testerHostSystem": "example tester host system",
            "tc001": true,
            "tc002": true,
            "tc003": false,
            "tc004": true,
            "tc005": true,
            "tc006": false,
            "tc007": false,
            "tc008": false,
            "tc009": false,
            "tc010": false,
            "comments": "tc003 failed because ..."
        }
    </pre>
</div>

In case the recommended format cannot be used, the test outcome can be shared with the IDX team in any other format (such as a table).

The test output should be sent through slack or to idx-interop-testing@sine.dev.

# Pilot Demonstrator # {#pilot-demonstrator}

The pilot demonstrator refers to the specific tests to be ran with real world data, provided by Upendo and to be shared with iGravity.

**Data flow**

1. Upendo uploads their data onto Leonardo's platform
1. Leonardo makes this data available through their IDX conformant API
1. ImpactableX consumes Leonardo's IDX conformant API
1. ImpactableX makes the data available (in a human readable fashion) to iGravity

The test cases and testing process (although this time unilateral) used for pilot testing should also be used for the pilot demonstrator.

Further feedback is, however, necessary, including the inputs of Upendo and iGravity.

Details about this feedback are still TBD.


<pre class=biblio>
{
    "IDX": {
      "authors": [ "Pompery, M.", "Henriques, R." ],
      "href": "https://sine-fdn.github.io/idx-protocol/",
      "title": "IDX Protocol"
    }
}
</pre>