<pre class='metadata'>
Title: IDX Interoperability Testing Guidance
Shortname: idx-interop-testing
Status: LD
ED: https://sine-fdn.github.io/interop-tesing.html
Canonical URL: ED
Editor: Martin Pompéry, https://sine.foundation, martin@sine.foundation
Editor: Raimundo Henriques, https://sine.foundation, raimundo@sine.foundation
Repository: sine-fdn/idx-protocol
Abstract: This document provides guidance on interoperability testing the [IDX protocol](./index.html).
Markup Shorthands: markdown yes
Boilerplate: omit conformance, omit copyright
Local Boilerplate: header yes
</pre>

# About # {#about}

This document details the  steps to be taken during interoperability testing between two host systems implementing the [IDX protocol](./index.html).

# Definitions # {#definitions}

: <dfn>Host System</dfn>
:: Software implementation conforming to the IDX protocol

: <dfn>Target Host System</dfn>
:: The [=host system=] being tested

: <dfn>Tester Host System</dfn>
:: The [=host system=] performing the tests

: <dfn data-noexport>Bilateral Testing</dfn>
:: The process through which two host systems mutually test their [=Interoperable|interoperability=]

: <dfn>Interoperable</dfn>
:: The quality of being able to exchange data between host systems irrespective of the vendors of the host systems, without the need for translation or transformation of the data

: <dfn data-noexport>Pilot Testing</dfn>
:: The first and most preliminary set of interoperability tests, less demanding than tests to be pursued in the near future, with the goal of adapting the technical specifications if need be

# Goals # {#goals}

The main goal of interoperability testing is two ensure that two host systems meet the minimum
requirements and are interoperable (see [[#pilot-testing-proc]]).

# Pilot Testing Process # {#pilot-testing-proc}

During pilot testing, two host systems shall exchange **mock data**. The goal is to ensure that the
two systems can exchange data according to the protocol and that such data is syntactically correct.

Pilot testing shall allow for more flexibility with regard to the features specified in the IDX
protocol than tests to be pursued in the future.

Accordingly, the [test cases](./index.html#test-cases) specified in Appendix B of the IDX protocol
tech specs will be divided into [[#mandatory-tests]] and [[#recommended-tests]].

Note: **All tests should be performed**, regardless of the host system's maturity. Learning how the
existing implementations respond to these specific requests will allow us to further refine the
technical specifications.

If all mandatory tests are passed, interoperability testing can continue and host systems can be
iteratively improved. If not, they need to be adapted and the tests repeated.

## Steps ## {#steps}

Pilot testing is bilateral and should be performed by following these steps:

**Phase 1**

1. Acting as the [=target host system=], host system A (e.g., Leonardo) provides host system B (e.g., ImpactableX) with
    1. The host url of their API
    1. A username
    1. A password
1. Acting as the **tester host system**, host system B (e.g., ImpactableX) performs both
        [[#mandatory-tests]] against host system A (e.g., Leonardo), keeping track of whether they are
        successful or otherwise.
1. The [=tester host system=], host system B documents the test outcome according to the instructions in
        [[#test-output]].

**Phase 2**

1. Acting as the [=target host system=], host system B (e.g., ImpactableX) provides host system A (e.g., Leonardo) with
    1. The host url of their API
    1. A username
    1. A password
1. Acting as the [=tester host system=], host system A (e.g., Leonardo) performs both [[#mandatory-tests]] agains host system B (e.g., ImpactableX), keeping track of whether they are successful or otherwise.
1. The tester host system, host system A documents the test outcome according to the instructions in [[#test-output]].

## Mandatory Tests ## {#mandatory-tests}

: [Test Case 001: AuthEndpoint Discovery](./index.html#tc-001)
:: Tests the target host system's ability to have a discoverable [AuthEndpoint](./index.html#authendpoint).

: [Test Case 002: Successful Authentication](./index.html#tc-002)
:: Tests the target host system's ability to [authenticate](./index.html#action-authenticate) a [data recipient](./index.html#data-recipient).

: [Test Case 005: Action OpportunityExchange without Limit](./index.html#tc-005)
:: Tests the target host system's ability to return [`Opportunity`](./index.html#elementdef-opportunity) data without a [Limit](./index.html#limit).

## Recommended Tests ## {#recommended-tests}

: [Test Case 003: Authentication with Invalid Credentials](./index.html#tc-003)
:: Tests the target host system's ability to handle invalid credentials during authentication.

: [Test Case 004: Malformed Authentication Request](./index.html#tc-004)
:: Tests the target host system's ability to handle malformed authentication requests.

: [Test Case 006: Action OpportunityExchange Pagination](./index.html#tc-006)
:: Tests the target host system's ability to paginate [`Opportunity`](./index.html#elementdef-opportunity) data.

: [Test Case 007: Action OpportunityExchange with Malformed Limit](./index.html#tc-007)
:: Tests the target host system's ability to handle a malformed `limit` parameter.

: [Test Case 008: Action OpportunityExchange with Invalid Token](./index.html#tc-008)
:: Tests the target host system's ability to handle an invalid access token.

: [Test Case 009: Action OpportunityExchange with Expired Token](./index.html#tc-009)
:: Tests the target host system's ability to handle an expired access token.

: [Test Case 010: Malformed OpportunityExchange Request](./index.html#tc-010)
:: Tests the target host system's ability to handle malformed requests to the `[Subpath]/1/opportunities`.

## Test Output ## {#test-output}

Once all tests are performed, the tester host system is asked to provide the IDX team with a document summarizing the outcome of the test.

We recommend that this document is JSON with the format specified [here](./index.html#test-output)
and that the (free form) `comments` field is used to describe why certain tests failed or were
skipped.

<div class=example>
    <pre highlight=json>
        {
            "targetHostSystem": "example target host system",
            "testerHostSystem": "example tester host system",
            "tc001": true,
            "tc002": true,
            "tc003": false,
            "tc004": true,
            "tc005": true,
            "tc006": false,
            "tc007": false,
            "tc008": false,
            "tc009": false,
            "tc010": false,
            "comments": "tc003 failed because ..."
        }
    </pre>
</div>

In case the recommended format cannot be used, the test outcome can be shared with the IDX team in any other format (such as a table).

The test output should be sent through slack or to raimundo@sine.foundation.

# Pilot Demonstrator # {#pilot-demonstrator}

The pilot demonstrator refers to the specific tests to be ran with real world data, provided by Upendo and to be shared with iGravity.

**Data flow**

1. Upendo uploads their data onto Leonardo's platform
1. Leonardo makes this data available through their IDX conformant API
1. ImpactableX consumes Leonardo's IDX conformant API
1. ImpactableX makes the data available (in a human readable fashion) to iGravity

The test cases and testing process (although this time unilateral) used for pilot testing should also be used for the pilot demonstrator.

Further feedback is, however, necessary, including the inputs of Upendo and iGravity.

Details about this feedback are still TBD.
